In [1]:
import psycopg2
import os 
from dotenv import load_dotenv
from utils import sentence_aware_chunker
from langchain_community.document_loaders import PyPDFLoader

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\panlw\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
c:\Users\panlw\Desktop\ML-helper-RAG\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Chunk 1: Machine learning is a subset of AI. It enables computers to learn from data.
Chunk 2: It enables computers to learn from data. Neural networks are inspired by the brain.
Chunk 3: Neural networks are inspired by the brain. They consist of layers of neurons.
Chunk 4: They consist of layers of neurons. Deep learning uses many layers.

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 105/105 [00:00<00:00, 8395.00it/s]

In [2]:
import pandas as pd
load_dotenv()
CONNECTION_STRING = os.getenv('CONNECTION_KEY')
collection_name = 'ML knowledge v2'

In [35]:
load_dotenv()
CONNECTION_STRING = os.getenv('CONNECTION_KEY')
collection_name = 'ML knowledge v2'

conn = psycopg2.connect(CONNECTION_STRING)
cur = conn.cursor()
cur.execute("""
EXPLAIN ANALYZE
SELECT document
FROM langchain_pg_embedding
WHERE collection_id = (SELECT uuid FROM langchain_pg_collection LIMIT 1)
LIMIT 5



""")

rows = cur.fetchall()
col_names = [desc[0] for desc in cur.description]
df = pd.DataFrame(rows, columns = col_names)
df

                                           QUERY PLAN
0   Limit  (cost=0.02..2.98 rows=5 width=720) (act...
1                      Buffers: shared hit=3 read=395
2                                          InitPlan 1
3       ->  Limit  (cost=0.00..0.02 rows=1 width=1...
4                              Buffers: shared read=1
5             ->  Seq Scan on langchain_pg_collect...
6                              Buffers: shared read=1
7     ->  Seq Scan on langchain_pg_embedding  (cos...
8           Filter: (collection_id = (InitPlan 1)....
9                        Rows Removed by Filter: 2935
10                     Buffers: shared hit=3 read=395
11                                          Planning:
12                     Buffers: shared hit=178 read=5
13                            Planning Time: 3.901 ms
14                           Execution Time: 8.249 ms

In [15]:
load_dotenv()
CONNECTION_STRING = os.getenv('CONNECTION_KEY')
collection_name = 'ML knowledge v2'

conn = psycopg2.connect(CONNECTION_STRING)
cur = conn.cursor()
cur.execute("""
    SELECT 
        tablename, indexname, indexdef
    FROM pg_indexes
    WHERE tablename = 'langchain_pg_embedding';
""")

rows = cur.fetchall()
col_names = [desc[0] for desc in cur.description]
df = pd.DataFrame(rows, columns = col_names)
df

,tablename,indexname,indexdef
0,langchain_pg_embedding,langchain_pg_embedding_pkey,CREATE UNIQUE INDEX langchain_pg_embedding_pke...
1,langchain_pg_embedding,ix_cmetadata_gin,CREATE INDEX ix_cmetadata_gin ON public.langch...
2,langchain_pg_embedding,idx_embedding_hnsw,CREATE INDEX idx_embedding_hnsw ON public.lang...